#yolov8pose使用openvino进行部署的配置文件

model_path: "/home/xiaoyiming/task8/vino_task/src/YoloVino/model/yolov5n_0714_15000_cv.xml" #模型路径
device_type: "CPU" #使用的设备类型，一般是CPU或者GPU

#下面内容为可选，是为了便于日志记录器进行输出

model_type: "YOLO-V5-FOURPOINT" #模型类型
input_size: "640" #模型的输入图像尺寸
output_size: "[1,25200,22]" #模型的输出尺寸
date: "2025/09/19" #修改该yaml的日期